[App]
Name = "ai.h2o.wave.twitter-sentiment"
Version = "0.1.0"
Title = "Twitter Sentiment"
Description = "App for searching twitter hashtags and sentiment analysis"
LongDescription="about.md"
Category = "Data Science"
Keywords =  ["Data Science", "Wave", "Open Source", "Sentiment Analysis"]

[Runtime]
Module = "src.app"
MemoryReservation = "4Gi"
MemoryLimit = "6Gi"
