[App]
Name = "ai.h2o.wave.walmart-forecasting"
Version = "0.2.1"
Title = "Sales Forecasting"
Description = "Demo to explore demand and forecasts for supply chain optimization."
LongDescription = "about.md"
Category = "Retail"
Keywords = ["sales", "time-series", "walmart"]

[Runtime]
Module = "wave-forecast"

[[Env]]
Name = "AWS_ACCESS_KEY_ID"
Secret = "h2o-s3-readonly"
SecretKey = "accessKey"

[[Env]]
Name = "AWS_SECRET_ACCESS_KEY"
Secret = "h2o-s3-readonly"
SecretKey = "secretKey"
