[App]
Name = "ai.h2o.wave.walmart-forecasting"
Version = "0.1.0"
Title = "Sales Forecasting"
Description = "Exploring historic demand and forecasts for supply chain optimization"
Category = "Retail"
Keywords = [""]

[Runtime]
Module = "wave-forecast"

[[Env]]
Name = "AWS_ACCESS_KEY_ID"
Secret = "h2o-s3-readonly"
SecretKey = "accessKey"

[[Env]]
Name = "AWS_SECRET_ACCESS_KEY"
Secret = "h2o-s3-readonly"
SecretKey = "secretKey"
