
[App]
Name = "ai.h2o.wave.walmart-forecasting"
Version = "0.1.0"
Title = "Sales Forecasting"
Description = "Exploring historic demand and forecasts for supply chain optimization"
Category = "Retail"
Keywords = [""]

[Runtime]
Module = "wave-forecast"
