[App]
Name = "ai.h2o.wave.shopping-cart-recommendations"
Version = "0.1.0"
Title = "Shopping Cart Recommendations"
Description = "Recommendations based on shopping cart items"
LongDescription="about.md"
Category = "Data Science"
Keywords = ["Data Science", "Wave", "Open Source", "Market Basket Analysis"]

[Runtime]
Module = "src.app"
MemoryReservation = "4Gi"
MemoryLimit = "6Gi"
