[App]
Name = "ai.h2o.wave.credit-risk"
Version = "0.2.0"
Title = "Credit Card Risk"
Description = "Application which allows a business user to review model predictions on whether or not someone will pay off their credit card"
Category = "Data Science"
Keywords = ["Data Science", "Wave", "Open Source"]

[Runtime]
Module = "src.app"
MemoryReservation = "4Gi"
MemoryLimit = "6Gi"
