[App]
Name = "ai.h2o.wave.credit-risk"
Version = "0.1.01"
Title = "Credit Card Risk"
Description = "Demo for business users to review and update model predictions."
LongDescription = "about.md"
Category = "Data Science"
Keywords = ["Data Science", "Wave", "Open Source"]

[Runtime]
Module = "src.app"
MemoryReservation = "4Gi"
MemoryLimit = "6Gi"
