[App]
Name = "ai.h2o.wave.churn-risk"
Version = "0.1.0"
Title = "Telco Churn Risk"
Description = "Demo to predict churn risk of telco customers and display top reason codes."
Category = "Data Science"
Keywords = ["Data Science", "Wave", "Open Source"]

[Runtime]
Module = "src.app"
MemoryReservation = "4Gi"
MemoryLimit = "6Gi"
