[App]
Name = "ai.h2o.wave.churn-risk"
Version = "1.0.0"
Title = "Home Insurance Churn Risk"
Description = "Demo to predict churn risk of insurance customers and display top reason codes."
LongDescription = "about.md"
Category = "Insurance"
Keywords = ["Insurance", "Wave", "Open Source"]

[Runtime]
Module = "src.app"
MemoryReservation = "8Gi"
MemoryLimit = "10Gi"
