[App]
Name = "ai.h2o.wave.explaining-ratings"
Version = "0.1.0"
Title = "Explainable Ratings"
Description = "Demo for business users to visually understand NLP model predictions."
LongDescription = "about.md"
Category = "Data Science"
Keywords = ["Data Science", "Wave", "Open Source"]

[Runtime]
Module = "src.app"
MemoryReservation = "4Gi"
MemoryLimit = "6Gi"
